/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;
import javax.swing.*;
import java.awt.*;
//gui of accommodationSelectionPage
public class AccommodationSelectionPage extends JFrame {

    public AccommodationSelectionPage() {
        setTitle("Accommodation Selection");
        setSize(500, 400);  // Increased size for better layout
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setLocationRelativeTo(null);  // Center the window on screen

        // Setting up the font and colors
        Font labelFont = new Font("Arial", Font.BOLD, 14);
        Font comboBoxFont = new Font("Arial", Font.PLAIN, 14);
        Font buttonFont = new Font("Arial", Font.BOLD, 14);
        Color bgColor = new Color(245, 245, 245);  // Light gray background color
        Color buttonColor = new Color(60, 179, 113);  // Medium sea green button color
        Color buttonTextColor = Color.WHITE;

        // Set background color
        getContentPane().setBackground(bgColor);

        // Components
        JLabel lblAccommodation = new JLabel("Select an Accommodation:");
        lblAccommodation.setFont(labelFont);

        String[] accommodationOptions = { "Hotel", "Hostel", "Resort" };
        JComboBox<String> comboAccommodation = new JComboBox<>(accommodationOptions);
        comboAccommodation.setFont(comboBoxFont);

        JButton btnSelectAccommodation = new JButton("Select Accommodation");
        btnSelectAccommodation.setBackground(buttonColor);
        btnSelectAccommodation.setForeground(buttonTextColor);
        btnSelectAccommodation.setFont(buttonFont);

        JButton btnBack = new JButton("Back to Dashboard");
        btnBack.setBackground(buttonColor);
        btnBack.setForeground(buttonTextColor);
        btnBack.setFont(buttonFont);

        // Add action listener to create an accommodation using AccommodationFactory
        btnSelectAccommodation.addActionListener(e -> {
            String selectedAccommodation = (String) comboAccommodation.getSelectedItem();
            Accommodation accommodation = AccommodationFactory.getAccommodation(selectedAccommodation);
            
            // Use the BookingManager to book the selected accommodation
            BookingManager.getInstance().bookHotel(accommodation.getAccommodationType(), "2024-12-25");

            JOptionPane.showMessageDialog(this, "Booked " + accommodation.getAccommodationType());
        });

        btnBack.addActionListener(e -> goBack());

        // Using GridBagLayout for an organized structure
        setLayout(new GridBagLayout());
        GridBagConstraints gbc = new GridBagConstraints();
        gbc.insets = new Insets(10, 10, 10, 10);  // Padding around components
        gbc.fill = GridBagConstraints.HORIZONTAL;

        // Add components to layout
        gbc.gridx = 0;
        gbc.gridy = 0;
        add(lblAccommodation, gbc);

        gbc.gridx = 1;
        gbc.gridy = 0;
        add(comboAccommodation, gbc);

        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.gridwidth = 2;
        add(btnSelectAccommodation, gbc);

        gbc.gridy = 2;
        add(btnBack, gbc);
    }

    private void goBack() {
        new MainDashboard().setVisible(true);
        this.dispose();
    }

    public static void main(String[] args) {
        SwingUtilities.invokeLater(() -> new AccommodationSelectionPage().setVisible(true));
    }
}



/**
 *
 * @author icc
 */

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 483, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 342, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
      
        //</editor-fold>


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
